### PR TITLE
Misc fixes to allow dynamic mailer name and dynamic wait while sendin…

### PR DESCRIPTION
**Pull request by ausangshukla**
…g emails

## Pull Request

**Summary:**
These changes enable for mailer and wait to take method names as symbols

**Related Issue:**

**Description:**
Its a pretty simple change
1. mailer = evaluate_option(:mailer), to enable the mailer to be dynamic and based on a method defined in the event.
2. option.is_a?(Symbol) && context.event.respond_to?(option), allows the wait time to be dynamic and based on a method call.

**Testing:**
Ive run my applications tests against this, but have not written any new tests specifically for these changes.

**Screenshots (if applicable):**

**Checklist:**

- [ ] Code follows the project's coding standards
- [ ] Tests have been added or updated to cover the changes
- [ ] Documentation has been updated (if applicable)
- [ ] All existing tests pass
- [ ] Conforms to the contributing guidelines

**Additional Notes:**

### CODE REVIEW

**Comment by excid3** [comment]
I actually just commited a fix here: https://github.com/excid3/noticed/commit/8da57f851914d30ddd6ee773e06274bf0ef4fdcc

Is there a case this doesn't handle?

**Comment by ausangshukla** [comment]
This may work for the dynami mailer, but not for the wait time.

**Comment by excid3** [comment]
Can you provide an example?

**Comment by ausangshukla** [comment]
This is what I have in my actual prod code. The reason is to prevent aws from getting flooded, which results in throttling errors. So we need to delay the sending of emails. However when sending a bunch of emails, we cant use the same delay, we need to spread the delay over some period, by randomizing it, so that aws does not get flooded. Hope this makes sense

deliver_by :email do |config|
      config.mailer = :mailer_name
      config.method = :email_method
      config.params = :email_data
      config.wait = :email_delay
 end


def email_delay(_notification = nil)
    # Randomize the delay so we dont flood aws SES
    delay_seconds = entity.entity_setting.email_delay_seconds
    delay_seconds = delay_seconds.positive? ? rand(1..delay_seconds) : rand(1..300)
    Rails.env.development? ? 0 : delay_seconds
 end

**Comment by ausangshukla** [comment]
I agree with your changes in https://github.com/excid3/noticed/commit/8da57f851914d30ddd6ee773e06274bf0ef4fdcc, can replace the one I suggested, for dynamic mailer

**Comment by ausangshukla** [comment]
Also note that in version < 2 I could do the following
deliver_by :email, mailer: :mailer_name, method: :email_method, format: :email_data, delay: :email_delay

And the delay would be dynamic, this is the prob Im trying to solve above.

**Comment by excid3** [comment]
Wait should already work, but it will be evaluated against methods in the `notification_methods` block since it would apply to the individual recipients.

**Comment by ausangshukla** [comment]
Makes sense, thank you for clarifying. Appreciate it.

**Pull request closed without merging**
